spring.application.name=movie-ticket-booking

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/movie_ticket_booking}
spring.datasource.username=${DB_USERNAME:movie_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

booking.hold-duration-minutes=5

pricing.premium-seat-surcharge=50.00
pricing.weekend-surcharge=25.00

app.bootstrap.enabled=${APP_BOOTSTRAP_ENABLED:true}
app.bootstrap.admin.email=${ADMIN_EMAIL:admin@moviebooking.local}
app.bootstrap.admin.password=${ADMIN_PASSWORD:admin123}
app.bootstrap.customer.email=${CUSTOMER_EMAIL:customer@moviebooking.local}
app.bootstrap.customer.password=${CUSTOMER_PASSWORD:customer123}
